### ISSUE TITLE
Compiler reports warning (too many warnings - 4591) even when all have been ignored

### ISSUE THREAD

**Issue by beeb** [foundry-rs/compilers#167]
I'm working on a very big repo with very big files, and our test fixtures and contracts are very big.

As such, solc creates warnings for all of those (contract size too big), and we have more than 256.

In the code below, the library ignores warnings 1878 and 5574 for test files, which is fine.

https://github.com/foundry-rs/compilers/blob/67a46cf8e60fd5d8da9b26d14f3d72288c5bbc7c/crates/compilers/src/compile/output/mod.rs#L925-L952

However, we still see the following in the output:

```
Compiler run successful with warnings:
Warning (4591): There are more than 256 warnings. Ignoring the rest.
```

It's really confusing to see this message when all of the warnings have been ignored by `foundry_compilers`.

The clean solution would probably be the following:

- Count the number of ignored warnings
- Count the number of non-ignored warnings
- If non-ignored warnings <= 256 && ignored warnings > 256, then silence error 4591

The `ErrorFilter` should probably be updated to match.

**Comment by mattsse** [comment]
could you please share your foundry.toml settings for this?

**Comment by beeb** [comment]
```toml
[profile.default]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000
libs = ["node_modules", "lib"]
invariant = { fail_on_revert = true }

remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "solady/src/=node_modules/solady/src/",
]

[profile.default.fmt]
line_length = 120
bracket_spacing = true
wrap_comments = true
number_underscore = "thousands"
sort_imports = true
```
